# docker-compose.yml
services:
  user-service:
    build: ./user-service
    ports:
      - "3001:3001"
    networks:
      - twitter-net

  tweet-service:
    build: ./tweet-service
    ports:
      - "3002:3002"
    networks:
      - twitter-net
    depends_on:
      - rabbitmq
      - user-service
    environment:
      RABBITMQ_HOST: rabbitmq

  timeline-service:
    build: ./timeline-service
    ports:
      - "3003:3003"
    container_name: timeline-service
    networks:
      - twitter-net
    depends_on:
      - tweet-service

  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: rabbitmq
    ports:
      - "15672:15672"  # RabbitMQ Management UI
      - "5672:5672"    # RabbitMQ Default port
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    networks:
      - twitter-net

networks:
  twitter-net:
    driver: bridge
